parameters:
    api.class:   SkreenHouseFactory\v3Bundle\Api\ApiManager
    api.format:  .json
    api.env:     %kernel.environment%

services:
    api:
        class:        %api.class%
        arguments:    [%api.env%, %api.format%]
        calls:
            - [ setLogger, [ @logger ] ]
        tags:
            - { name: monolog.logger, channel: api_calls }

#twig:
#    globals:
#        fb_prod:
#          app_id: 