#main
homepage:
    pattern:  /
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Main:home }
homepage_locale:
    pattern:  /{_locale}
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Main:home }
    requirements:
        _locale: en|fr