#main
homepage:
    pattern:  /
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Main:home }

#player
player_live:
    pattern:  /les-chaines-en-direct
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Player:live }
player_redirect:
    pattern:  /redirect
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Player:redirect }
player:
    pattern:  /{_locale}/player
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Player:player }

#playlist
playlist_load:
    #pattern:  /playlist/{session_uid}/{type}
    pattern:  /www/slider/queue/{session_uid}/access/{type}.json
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Session:playlist }
    requirements:
        type: .*