#embed
embed_offer:
    pattern:  /video/{id}/
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Embed:video }
    requirements:
        id: \d+

#main
postproxy:
    pattern:  /proxy
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Main:proxy }
sitemap_mrss:
    pattern:  /sitemap.xml
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Main:sitemap }
header:
    pattern:  /header/
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Main:header }
homes_vod:
    pattern:  /video-a-la-demande/{home}/
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Main:home }
    requirements:
        home: film|serie|documentaire|emission|spectacle|jeunesse
homes:
    pattern:  /{home}/
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Main:home, home: null }
    requirements:
        home: |video-a-la-demande|cinema|tv-replay|film|serie|documentaire|emission|spectacle|films|series|documentaires|emissions|spectacles|vod|jeunesse

#timeline
timelinejs:
    pattern:  /__timeline/
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Timeline:timelinejs }
tvgrid_addchannel:
    pattern:  /programme-tv/addchannel/
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Timeline:addchannel }
tvgrid_date:
    pattern:  /programme-tv/{date}/
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Timeline:grid }
tvgrid:
    pattern:  /programme-tv/
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Timeline:grid }

#sitemaps
sitemap_channels_page:
    pattern:  /channels/{type}/{page}/
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Sitemap:channels }
sitemap_channels:
    pattern:  /channels/{type}/
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Sitemap:channels }

#selections
selections:
    pattern:  /{homeslug}/selection/{id}-{slug}/
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Content:selection }
    requirements:
        id: \d+
        slug: "[^/]+"
        homeslug: "[^/]+"
v2_selections:
    pattern:  /selection/{id}-{slug}/
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Content:selection }
    requirements:
        id: \d+
        slug: "[^/]+"

#search
search_format:
    pattern:  /{format}/search/{q}/
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Main:search }
    requirements:
        q: "[^/]+"
search:
    pattern:  /programmes/{q}/
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Main:search }
    requirements:
        q: "[^/]+"

#user
user_settings:
    pattern:  /user/settings/
    defaults: { _controller: SkreenHouseFactoryV3Bundle:User:settings }
user_programs:
    pattern:  /user/programs/{onglet}
    defaults: { _controller: SkreenHouseFactoryV3Bundle:User:programs, onglet: null }
user_channels:
    pattern:  /user/programs/channel
    defaults: { _controller: SkreenHouseFactoryV3Bundle:User:programs, onglet: channel }
user_theaters:
    pattern:  /user/theaters/
    defaults: { _controller: SkreenHouseFactoryV3Bundle:User:theaters }
user_persons:
    pattern:  /user/persons/
    defaults: { _controller: SkreenHouseFactoryV3Bundle:User:persons }
user_vod:
    pattern:  /user/vod/{onglet}
    defaults: { _controller: SkreenHouseFactoryV3Bundle:User:vod, onglet: null }
user_playlist:
    pattern:  /user/{username}
    defaults: { _controller: SkreenHouseFactoryV3Bundle:User:playlist }
user_blacklist:
    pattern:  /newsletter/unsubscribe/
    defaults: { _controller: SkreenHouseFactoryV3Bundle:User:blacklist }
user_blacklist_notifications:
    pattern:  /notifications/unsubscribe/
    defaults: { _controller: SkreenHouseFactoryV3Bundle:User:blacklist, notifications: 1 }

#player
player_live:
    pattern:  /les-chaines-en-direct
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Player:live }
player_redirect:
    pattern:  /redirection/{type}/{name}/{title}/{episode}
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Player:redirect, target: null, template: redirect, episode: null }
    requirements:
        type: "[^/]+"
        target: "[^/]+"
        title: "[^/]+"
player_exit_with_infos:
    pattern:  /exit/{type}/{name}/{title}/{episode}
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Player:redirect, exit: 1, template: exit, episode: null }
    requirements:
        type: "[^/]+"
        target: "[^/]+"
        title: "[^/]+"
player_exit:
    pattern:  /exit/{target}
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Player:redirect, exit: 1, template: exit }
    requirements:
        target: ".*"
player_exit_get_url:
    pattern:  /exit
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Player:redirect, exit: 1, template: exit }
    requirements:
        target: "[^/]+"
player:
    pattern:  /player
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Player:player }

#api
playlist_load:
    pattern:  /www/slider/queue/{session_uid}/access/{type}.json
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Session:playlist }
    requirements:
        type: "[^/]+"

#persons
person_page:
    pattern:  /{type}/{id}-{slug}/page-{page}/
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Content:person }
    requirements:
        type: acteur|realisateur|presentateur|producteur|production|interprete|auteur|invite|editor|narration|divers|scenario|scenariste|invite|costume-designer|studio|autre|compositeur|musique|intervenant|realisateur-metteur-en-scene|production-designer|photographie|createur|montage|producteur-executif|son|decors|famille|voix-francaise|bruitage|co-producteur|maquillage|costumes|images|effets-speciaux|mise-en-scene|armurier|chanteur-lyrique|chef-monteur|chef-maquilleur|assistant-realisateur|musicien|scripte|d-apres-le-livre-de|d-apres-le-roman-de|d-apres|d-apres-un-sujet-original|d-apres-l-histoire-de|d-apres-l-oeuvre-de|d-apres-les-personnages-de|d-apres-une-nouvelle-de|d-apres-une-histoire-de|d-apres-un-sujet-original|direction-artistique|dialogues|cascades|chef-decorateur|combats|choregraphie|chef-coiffeur|chroniqueur|chef-operateur-son|casting|chef-d-orchestre|commentaires|adaptation|maquette|mixage|presse|accessoiriste|sportif|direction-orchestrale|story-board|societe-de-production|regisseur-general|documentation|interpretes|collection|chef-operateur-son
        id: \d+
        slug: "[^/]+"
        page: \d+
person:
    pattern:  /{type}/{id}-{slug}/
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Content:person }
    requirements:
        type: acteur|realisateur|presentateur|producteur|production|interprete|auteur|invite|editor|narration|divers|scenario|scenariste|invite|costume-designer|studio|autre|compositeur|musique|intervenant|realisateur-metteur-en-scene|production-designer|photographie|createur|montage|producteur-executif|son|decors|famille|voix-francaise|bruitage|co-producteur|maquillage|costumes|images|effets-speciaux|mise-en-scene|armurier|chanteur-lyrique|chef-monteur|chef-maquilleur|assistant-realisateur|musicien|scripte|d-apres-le-livre-de|d-apres-le-roman-de|d-apres|d-apres-un-sujet-original|d-apres-l-histoire-de|d-apres-l-oeuvre-de|d-apres-les-personnages-de|d-apres-une-nouvelle-de|d-apres-une-histoire-de|d-apres-un-sujet-original|direction-artistique|dialogues|cascades|chef-decorateur|combats|choregraphie|chef-coiffeur|chroniqueur|chef-operateur-son|casting|chef-d-orchestre|commentaires|adaptation|maquette|mixage|presse|accessoiriste|sportif|direction-orchestrale|story-board|societe-de-production|regisseur-general|documentation|interpretes|collection|chef-operateur-son
        id: \d+
        slug: "[^/]+"
# deprecated channel : before program !
channel_replay:
    pattern:  /replay/{id}-{slug}/
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Content:channel }
    requirements:
        id: \d+
        slug: "[^/]+"
channel_v2_format:
    pattern:  /{format}/sur-{slug}
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Content:channel }
    requirements:
        format: "[^/]+"
        slug: "[^/]+"
channel_v2_facet:
    pattern:  /{format}/{facet}/sur-{slug}
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Content:channel }
    requirements:
        format: "[^/]+"
        slug: "[^/]+"
        facet: "[^/]+"
channel_v2_facet2:
    pattern:  /{format}/{category}/{facet}/sur-{slug}
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Content:channel }
    requirements:
        format: "[^/]+"
        slug: "[^/]+"
        facet: "[^/]+"
        category: "[^/]+"
channel_v2:
    pattern:  /sur-{slug}
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Content:channel }
    requirements:
        slug: "[^/]+"
channels_v2_replay:
    pattern:  /replay/{id}-{slug}
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Content:channel }
    requirements:
        id: \d+
        slug: "[^/]+"

#content
program_dev:
    pattern:  /p/{id}
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Content:program }
    requirements:
        id: \d+
occurrence_v1:
    pattern:  /play/{id}
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Content:program, from_occurrence: 1 }
    requirements:
        id: \d+
program_v1:
    pattern:  /{format}/{id}-{slug}/{rubrique}/
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Content:program }
    requirements:
        id: \d+
        slug: "[^/]+"
        rubrique: seo|enligne|dvdbluray|bandeannonce|box|alatele|aucine|avertir|undefined
program_v2_pere:
    pattern:  /{format}/{idpere}-{slugpere}/{id}-{slug}
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Content:program }
    requirements:
        id: \d+
        slug: "[^/]+"
        idpere: \d+
        slugpere: "[^/]+"
program_v2:
    pattern:  /{format}/{id}-{slug}/
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Content:program }
    requirements:
        id: \d+
        slug: "[^/]+"
program_fils_saison:
    pattern:  /{format}/{categorie}/{idpere}-{slugpere}/{saison}/{id}-{slug}/
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Content:program }
    requirements:
        id: \d+
        slug: "[^/]+"
        idpere: \d+
        slugpere: "[^/]+"
        saison: "[^/]+"
        format: "[^/]+"
        categorie: "[^/]+"

program_fils_undefined:
    pattern:  /{format}/{categorie}/{idpere}-{slugpere}/{id}-{slug}/{rubrique}
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Content:program }
    requirements:
        id: \d+
        slug: "[^/]+"
        idpere: \d+
        slugpere: "[^/]+"
        format: "[^/]+"
        categorie: "[^/]+"
        rubrique: seo|enligne|dvdbluray|bandeannonce|box|alatele|aucine|avertir|undefined
program_pere_undefined:
    pattern:  /{format}/{categorie}/{id}-{slug}/{rubrique}
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Content:program }
    requirements:
        id: \d+
        slug: "[^/]+"
        format: "[^/]+"
        categorie: "[^/]+"
        rubrique: seo|enligne|dvdbluray|bandeannonce|box|alatele|aucine|avertir|undefined
program_fils:
    pattern:  /{format}/{categorie}/{idpere}-{slugpere}/{id}-{slug}/
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Content:program }
    requirements:
        id: \d+
        slug: "[^/]+"
        idpere: \d+
        slugpere: "[^/]+"
        format: "[^/]+"
        categorie: "[^/]+"
program_pere_saison:
    pattern:  /{format}/{categorie}/{id}-{slug}/saison-{season_number}/
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Content:program }
    requirements:
        id: \d+
        slug: "[^/]+"
        format: "[^/]+"
        categorie: "[^/]+"
        season_number: \d+
program_pere:
    pattern:  /{format}/{categorie}/{id}-{slug}/
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Content:program }
    requirements:
        id: \d+
        slug: "[^/]+"
        format: "[^/]+"
        categorie: "[^/]+"

#cinema
cinema_boxoffice:
    pattern:  /cinema/box-office/{alpha}
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Cinema:boxoffice }
    requirements:
        alpha: "[^/]+"
theaters_program:
    pattern:  /cinema/progam/{id}
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Cinema:program }
    requirements:
        id: \d+
theaters_search:
    pattern:  /cinema/search
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Cinema:search }

#categories
category_page:
    pattern:  /{format}/{category_slug}/page-{page}/
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Content:category }
    requirements:
        format: film|documentaire|serie|emission|journal|court-metrage|theatre|concert|clip|spectacle|telefilm|dessin-anime-et-manga|webserie
        category_slug: "[^/]+"
        page: \d+
category_facet:
    pattern:  /{format}/{category_slug}/{facet}/
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Content:category }
    requirements:
        format: film|documentaire|serie|emission|journal|court-metrage|theatre|concert|clip|spectacle|telefilm|dessin-anime-et-manga|webserie
        category_slug: "[^/]+"
        facet: "[^/]+"
category_facet_page:
    pattern:  /{format}/{category_slug}/{facet}/page-{page}/
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Content:category }
    requirements:
        format: film|documentaire|serie|emission|journal|court-metrage|theatre|concert|clip|spectacle|telefilm|dessin-anime-et-manga|webserie
        category_slug: "[^/]+"
        facet: "[^/]+"
        page: \d+
category_facet_access:
    pattern:  /{format}/{category_slug}/{facet}/{access}/
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Content:category }
    requirements:
        format: film|documentaire|serie|emission|journal|court-metrage|theatre|concert|clip|spectacle|telefilm|dessin-anime-et-manga|webserie
        category_slug: "[^/]+"
        access: video-a-la-demande|cinema
        facet: "[^/]+"
category_access:
    pattern:  /{category_slug}/{facet}/
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Content:category }
    requirements:
        format: film|documentaire|serie|emission|journal|court-metrage|theatre|concert|clip|spectacle|telefilm|dessin-anime-et-manga|webserie
        category_slug: video-a-la-demande|cinema
category:
    pattern:  /{format}/{category_slug}/
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Content:category }
    requirements:
        format: film|documentaire|serie|emission|journal|court-metrage|theatre|concert|clip|spectacle|telefilm|dessin-anime-et-manga|webserie
        category_slug: "[^/]+"
format_facet:
    pattern:  /{category_slug}/{facet}/
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Content:category }
    requirements:
        category_slug: film|documentaire|serie|emission|journal|court-metrage|theatre|concert|clip|spectacle|telefilm|dessin-anime-et-manga|webserie
        facet: "[^/]"
format_page:
    pattern:  /{category_slug}/page-{page}/
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Content:category }
    requirements:
        category_slug: film|documentaire|serie|emission|journal|court-metrage|theatre|concert|clip|spectacle|telefilm|dessin-anime-et-manga|webserie
        facet: "[^/]"
        page: \d+
format:
    pattern:  /{category_slug}/
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Content:category }
    requirements:
        category_slug: film|documentaire|serie|emission|journal|court-metrage|theatre|concert|clip|spectacle|telefilm|dessin-anime-et-manga|webserie

#cms
partenaires:
    pattern:  /partenaires/
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Cms:default, template: partners }

#cocons : before channel, important !
cocon_tv:
    pattern:  /{cocon}/{name}/
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Cms:cocon }
    requirements:
        cocon: video

#channel
channel_format_page:
    pattern:  /{slug}/{format}/page-{page}/
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Content:channel, page: null }
    requirements:
        slug: "[^/]+"
        facet: "[^/]+"
        format: film|documentaire|serie|emission|journal|court-metrage|theatre|concert|clip|spectacle|telefilm|dessin-anime-et-manga|webserie
channel_format_facet:
    pattern:  /{slug}/{format}/{facet}/
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Content:channel, facet: null }
    requirements:
        slug: "[^/]+"
        facet: "[^/]+"
        format: film|documentaire|serie|emission|journal|court-metrage|theatre|concert|clip|spectacle|telefilm|dessin-anime-et-manga|webserie
channel_format:
    pattern:  /{slug}/{format}/
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Content:channel }
    requirements:
        slug: "[^/]+"
        format: film|documentaire|serie|emission|journal|court-metrage|theatre|concert|clip|spectacle|telefilm|dessin-anime-et-manga|webserie
channel_page:
    pattern:  /{slug}/page-{page}/
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Content:channel }
    requirements:
        slug: "[^/]+"
        page: \d+
channel_facet:
    pattern:  /{slug}/{facet}/
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Content:channel }
    requirements:
        slug: "[^/]+"
        facet: "[^/]+"
channel:
    pattern:  /{slug}/
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Content:channel }
    requirements:
        slug: "[^/]+"

#cocons : end, after channel, important !
cocon_replay:
    pattern:  /{cocon}/{name}/
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Cms:cocon }
    requirements:
        cocon: tf1|france-2|france-3|m6|w9

#hack url generation
any_url:
    pattern:  /{url}
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Main:notfound }
    requirements:
        url: .*