#main
homepage:
    pattern:  /
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Main:home }
postproxy:
    pattern:  /post
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Main:post }

#user
user_programs:
    pattern:  /mes-programmes/{onglet}
    defaults: { _controller: SkreenHouseFactoryV3Bundle:User:programs, "onglet" = null }

#cinema
cinema_boxoffice:
    pattern:  /cinema/box-office/{alpha}
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Cinema:boxoffice }
    requirements:
        alpha: .*

#player
player_live:
    pattern:  /les-chaines-en-direct
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Player:live }
player_redirect:
    pattern:  /redirection/{target}
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Player:redirect, "target" = null }
    requirements:
        target: .*
player:
    pattern:  /player
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Player:player }

#api
playlist_load:
    pattern:  /www/slider/queue/{session_uid}/access/{type}.json
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Session:playlist }
    requirements:
        type: .*