#main
postproxy:
    pattern:  /proxy
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Main:proxy }
homes:
    pattern:  /{home}/
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Main:home, home: null }
    requirements:
        home: |video-a-la-demande|cinema|tv-replay|film|serie|documentaire|emission|spectacle
        
selections:
    pattern:  /{homeslug}/selection/{id}-{slug}/
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Content:selection }
    requirements:
        id: \d+
        slug: "[^/]+"
        homeslug: "[^/]+"
v2_selections:
    pattern:  /selection/{id}-{slug}/
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Content:selection }
    requirements:
        id: \d+
        slug: "[^/]+"

#search
search:
    pattern:  /programmes/{q}/
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Main:search }
    requirements:
        q: "[^/]+"

#user
user_programs:
    pattern:  /mes-programmes/{onglet}
    defaults: { _controller: SkreenHouseFactoryV3Bundle:User:programs, onglet: null }
user_playlist:
    pattern:  /playlist/{username}
    defaults: { _controller: SkreenHouseFactoryV3Bundle:User:playlist }
user_blacklist:
    pattern:  /newsletter/unsubscribe
    defaults: { _controller: SkreenHouseFactoryV3Bundle:User:blacklist }
user_blacklist_notifications:
    pattern:  /notifications/unsubscribe
    defaults: { _controller: SkreenHouseFactoryV3Bundle:User:blacklist, notifications: 1 }

#cinema
cinema_boxoffice:
    pattern:  /cinema/box-office/{alpha}
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Cinema:boxoffice }
    requirements:
        alpha: "[^/]+"

#player
player_live:
    pattern:  /les-chaines-en-direct
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Player:live }
player_redirect:
    pattern:  /redirection/{target}
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Player:redirect, target: null, template: redirect }
    requirements:
        target: "[^/]+"
player_exit_with_infos:
    pattern:  /exit/{type}/{name}/{title}
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Player:redirect, exit: 1, template: exit }
    requirements:
        type: "[^/]+"
        target: "[^/]+"
        title: "[^/]+"
player_exit:
    pattern:  /exit/{target}
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Player:redirect, exit: 1, template: exit }
    requirements:
        target: "[^/]+"
player_exit_get_url:
    pattern:  /exit
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Player:redirect, exit: 1, template: exit }
    requirements:
        target: "[^/]+"
player:
    pattern:  /player
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Player:player }

#api
playlist_load:
    pattern:  /www/slider/queue/{session_uid}/access/{type}.json
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Session:playlist }
    requirements:
        type: "[^/]+"


#personnes
person_page:
    pattern:  /{type}/{id}-{slug}/page-{page}
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Content:person }
    requirements:
        type: acteur|realisateur|presentateur|producteur|interprete
        id: \d+
        slug: "[^/]+"
        page: \d+
person:
    pattern:  /{type}/{id}-{slug}/
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Content:person }
    requirements:
        type: acteur|realisateur|presentateur|producteur|interprete
        id: \d+
        slug: "[^/]+"

# deprecated channel : before program !

channel_replay:
    pattern:  /replay/{id}-{slug}/
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Content:channel }
    requirements:
        id: \d+
        slug: "[^/]+"
channel_v2_format:
    pattern:  /{format}/sur-{slug}
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Content:channel }
    requirements:
        slug: "[^/]+"
channel_v2_facet:
    pattern:  /{format}/{facet}/sur-{slug}
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Content:channel }
    requirements:
        slug: "[^/]+"
channel_v2:
    pattern:  /sur-{slug}
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Content:channel }
    requirements:
        slug: "[^/]+"
channels_v2_replay:
    pattern:  /replay/{id}-{slug}
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Content:channel }
    requirements:
        id: \d+
        slug: "[^/]+"

#content
program_dev:
    pattern:  /p/{id}
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Content:program }
    requirements:
        id: \d+
program_v2_pere:
    pattern:  /{format}/{idpere}-{slugpere}/{id}-{slug}
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Content:program }
    requirements:
        id: \d+
        slug: "[^/]+"
        idpere: \d+
        slugpere: "[^/]+"
program_v2:
    pattern:  /{format}/{id}-{slug}
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Content:program }
    requirements:
        id: \d+
        slug: "[^/]+"
program_fils_saison:
    pattern:  /{format}/{categorie}/{idpere}-{slugpere}/{saison}/{id}-{slug}/
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Content:program }
    requirements:
        id: \d+
        slug: "[^/]+"
        idpere: \d+
        slugpere: "[^/]+"
        saison: "[^/]+"
        format: "[^/]+"
        categorie: "[^/]+"
program_fils:
    pattern:  /{format}/{categorie}/{idpere}-{slugpere}/{id}-{slug}/
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Content:program }
    requirements:
        id: \d+
        slug: "[^/]+"
        idpere: \d+
        slugpere: "[^/]+"
        format: "[^/]+"
        categorie: "[^/]+"
program_pere_saison:
    pattern:  /{format}/{categorie}/{id}-{slug}/saison-{season_number}/
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Content:program }
    requirements:
        id: \d+
        slug: "[^/]+"
        format: "[^/]+"
        categorie: "[^/]+"
        season_number: \d+
program_pere:
    pattern:  /{format}/{categorie}/{id}-{slug}/
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Content:program }
    requirements:
        id: \d+
        slug: "[^/]+"
        format: "[^/]+"
        categorie: "[^/]+"
programtheater:
    pattern:  /program/theaters/{id}
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Cinema:program }
    requirements:
        id: \d+

#categories
category_page:
    pattern:  /{format}/{category_slug}/page-{page}/
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Content:category }
    requirements:
        format: film|documentaire|serie|emission|journal|court-metrage|theatre|concert|spectacle|telefilm|dessin-anime-et-manga
        category_slug: "[^/]+"
        page: \d+
category_facet:
    pattern:  /{format}/{category_slug}/{facet}/
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Content:category }
    requirements:
        format: film|documentaire|serie|emission|journal|court-metrage|theatre|concert|spectacle|telefilm|dessin-anime-et-manga
        category_slug: "[^/]+"
        facet: "[^/]+"
category:
    pattern:  /{format}/{category_slug}/
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Content:category }
    requirements:
        format: film|documentaire|serie|emission|journal|court-metrage|theatre|concert|spectacle|telefilm|dessin-anime-et-manga
        category_slug: "[^/]+"

#channel
channel_format_facet:
    pattern:  /{slug}/{format}/{facet}/
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Content:channel, facet: null }
    requirements:
        slug: "[^/]+"
        facet: "[^/]+"
        format: film|documentaire|serie|emission|journal|court-metrage|theatre|concert|spectacle|telefilm|dessin-anime-et-manga
channel_page:
    pattern:  /{slug}/page-{page}/
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Content:channel }
    requirements:
        slug: "[^/]+"
        page: \d+

#cocons : end, important !
cocon_tv:
    pattern:  /{cocon}/{name}/
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Cms:cocon, domain: replay }
    requirements:
        cocon: video|tf1|france2|france-3|m6|w9

channel_facet:
    pattern:  /{slug}/{facet}
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Content:channel }
    requirements:
        slug: "[^/]+"
        facet: "[^/]+"
channel:
    pattern:  /{slug}/
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Content:channel }
    requirements:
        slug: "[^/]+"

#hack url generation
any_url:
    pattern:  /{url}
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Main:404 }
    requirements:
        url: .*