#user
user_settings:
    pattern:  /user/settings/
    defaults: { _controller: SkreenHouseFactoryV3Bundle:User:settings }
user_programs:
    pattern:  /user/programs/{onglet}
    defaults: { _controller: SkreenHouseFactoryV3Bundle:User:programs, onglet: null }
user_channels:
    pattern:  /user/programs/channel
    defaults: { _controller: SkreenHouseFactoryV3Bundle:User:programs, onglet: channel }
user_theaters:
    pattern:  /user/theaters/
    defaults: { _controller: SkreenHouseFactoryV3Bundle:User:theaters }
user_persons:
    pattern:  /user/persons/
    defaults: { _controller: SkreenHouseFactoryV3Bundle:User:persons }
user_svod:
    pattern:  /user/svod/
    defaults: { _controller: SkreenHouseFactoryV3Bundle:User:svod }
user_vod:
    pattern:  /user/vod/{onglet}
    defaults: { _controller: SkreenHouseFactoryV3Bundle:User:vod, onglet: null }
user_playlist:
    pattern:  /user/{username}
    defaults: { _controller: SkreenHouseFactoryV3Bundle:User:playlist }
user_blacklist:
    pattern:  /newsletter/unsubscribe/
    defaults: { _controller: SkreenHouseFactoryV3Bundle:User:blacklist }
user_blacklist_notifications:
    pattern:  /notifications/unsubscribe/
    defaults: { _controller: SkreenHouseFactoryV3Bundle:User:blacklist, notifications: 1 }
